// <auto-generated />
using System;
using HealthConnect.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HealthConnect.Migrations
{
    [DbContext(typeof(HealthConnectContext))]
    partial class HealthConnectContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HealthConnect.Models.Doctor_approvel", b =>
                {
                    b.Property<int>("doctor_approvel_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("doctor_approvel_id"));

                    b.Property<string>("House_number_and_Street_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("account_approve")
                        .HasColumnType("bit");

                    b.Property<DateTime>("account_create_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("clinic_or_hospital_address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("currency_code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dob")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("doctor_qualifications")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("doctor_specialitis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("doctor_type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("doctore_experience")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("doctore_medical_license_photo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hospital_or_clinic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isactive")
                        .HasColumnType("bit");

                    b.Property<string>("languages_spoken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("medical_registration_no")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("medicine_type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mobil_no")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("on_site_consultation_fee")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pincode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("profile_pic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("state")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("state_medical_council")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("video_call_consultation_fee")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("year_of_registration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("doctor_approvel_id");

                    b.ToTable("Doctor_approvel", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
